name: Bun Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bun-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format
        run: bun run format

      # - name: Commit formatted files
      #   uses: stefanzweifel/git-auto-commit-action@v5

  bun-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

  bun-build:
    needs: [bun-format, bun-lint]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: Prisma Migrate
        run: bunx prisma migrate dev --preview-feature
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: Prisma Generate
        run: bunx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
