name: Fix Code Style

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
